# Generated by Django 4.2.1 on 2023-05-21 07:54

from django.db import migrations, models
import django.utils.timezone
from ckeditor.fields import RichTextField


class Migration(migrations.Migration):

    dependencies = [
        ("jjit", "0002_auto_20230504_1950"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="article/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
