# Generated by Django 4.2.1 on 2023-05-21 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jjit", "0003_remove_question_subject_question_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jjit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(upload_to="jjit/"),
        ),
    ]
