# Generated by Django 4.2.1 on 2023-06-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjit", "0006_answer_writer_question_like_question_writer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
