# Generated by Django 4.2.2 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0002_rename_name_project_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFREN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SOUP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1000)),
            ],
        ),
    ]
