# Generated by Django 4.2.1 on 2023-06-03 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #("articleapp", "0004_alter_article_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commentapp", "0002_comment_parent_comment_alter_comment_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment",
                to="articleapp.article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
