# Generated by Django 4.2.2 on 2023-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0005_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.AddField(
            model_name="article",
            name="hits",
            field=models.PositiveIntegerField(default=1, verbose_name="조회수"),
        ),
    ]
