# Generated by Django 4.2.2 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0006_remove_article_image_article_hits"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("has_answer", models.BooleanField(default=True)),
            ],
        ),
    ]
